"""
Project: Padex
File Created: 2026-03-03
Author: Xingnan Zhu
File Name: report.py
Description:
    Match report generation.
    Produces JSON analytics and HTML reports with embedded Plotly charts.
"""

from __future__ import annotations

from pathlib import Path

from padex.schemas.events import Point
from padex.schemas.tactics import MatchAnalytics
from padex.schemas.tracking import PlayerFrame
from padex.tactics.metrics import MetricsCalculator
from padex.viz.dashboard import MatchDashboard


class MatchReporter:
    """Generates match reports as JSON and HTML."""

    def __init__(
        self,
        metrics_calculator: MetricsCalculator | None = None,
    ) -> None:
        self._calc = metrics_calculator or MetricsCalculator()

    def compute(
        self,
        points: list[Point],
        player_frames: list[PlayerFrame],
        match_id: str,
    ) -> MatchAnalytics:
        """Compute all match analytics.

        Args:
            points: Segmented points with shots.
            player_frames: Player tracking data.
            match_id: Unique match identifier.

        Returns:
            MatchAnalytics with rally, player, and team metrics.
        """
        return self._calc.compute_match_analytics(
            points, player_frames, match_id
        )

    def to_json(
        self,
        analytics: MatchAnalytics,
        path: str | Path,
    ) -> None:
        """Write analytics to a JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            analytics.model_dump_json(indent=2), encoding="utf-8"
        )

    def to_html(
        self,
        analytics: MatchAnalytics,
        path: str | Path | None = None,
    ) -> str:
        """Generate an HTML report with embedded Plotly charts.

        Args:
            analytics: Computed match analytics.
            path: Optional file path to write. If None, returns HTML string only.

        Returns:
            HTML string.
        """
        dashboard = MatchDashboard()
        dashboard_fig = dashboard.generate(analytics)
        chart_html = dashboard_fig.to_html(
            full_html=False, include_plotlyjs="cdn"
        )

        summary_table = self._build_summary_table(analytics)
        player_table = self._build_player_table(analytics)
        team_table = self._build_team_table(analytics)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Match Report — {analytics.match_id}</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
            color: #333;
        }}
        h1 {{ color: #1565C0; border-bottom: 2px solid #1565C0; padding-bottom: 10px; }}
        h2 {{ color: #2E7D32; margin-top: 30px; }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 15px 0;
            background: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.12);
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px 14px;
            text-align: left;
        }}
        th {{ background: #1565C0; color: white; }}
        tr:nth-child(even) {{ background: #f9f9f9; }}
        .chart-container {{ margin: 20px 0; background: white; padding: 15px; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }}
        .footer {{ margin-top: 40px; color: #999; font-size: 0.85em; text-align: center; }}
    </style>
</head>
<body>
    <h1>Match Report: {analytics.match_id}</h1>
    <p>Schema version: {analytics.schema_version}</p>

    <h2>Summary</h2>
    {summary_table}

    <h2>Player Statistics</h2>
    {player_table}

    <h2>Team Statistics</h2>
    {team_table}

    <h2>Dashboard</h2>
    <div class="chart-container">
        {chart_html}
    </div>

    <div class="footer">
        Generated by Padex
    </div>
</body>
</html>"""

        if path is not None:
            path = Path(path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(html, encoding="utf-8")

        return html

    @staticmethod
    def _build_summary_table(analytics: MatchAnalytics) -> str:
        rm = analytics.rally_metrics
        if not rm:
            return "<p>No rally data available.</p>"

        total_points = len(rm)
        avg_rally = sum(r.rally_length for r in rm) / total_points
        avg_duration = sum(r.duration_ms for r in rm) / total_points / 1000
        total_wall = sum(r.wall_bounces for r in rm)

        return f"""<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total Points</td><td>{total_points}</td></tr>
<tr><td>Avg Rally Length</td><td>{avg_rally:.1f} shots</td></tr>
<tr><td>Avg Point Duration</td><td>{avg_duration:.1f}s</td></tr>
<tr><td>Total Wall Bounces</td><td>{total_wall}</td></tr>
</table>"""

    @staticmethod
    def _build_player_table(analytics: MatchAnalytics) -> str:
        if not analytics.player_metrics:
            return "<p>No player data available.</p>"

        rows = ""
        for pm in analytics.player_metrics:
            serve_pct = (
                f"{pm.serve_percentage * 100:.0f}%"
                if pm.serve_percentage is not None
                else "\u2014"
            )
            rows += f"""<tr>
<td>{pm.player_id}</td>
<td>{pm.total_shots}</td>
<td>{pm.winners}</td>
<td>{pm.errors}</td>
<td>{serve_pct}</td>
</tr>"""

        return f"""<table>
<tr><th>Player</th><th>Shots</th><th>Winners</th><th>Errors</th><th>Serve %</th></tr>
{rows}
</table>"""

    @staticmethod
    def _build_team_table(analytics: MatchAnalytics) -> str:
        if not analytics.team_metrics:
            return "<p>No team data available.</p>"

        rows = ""
        for tm in analytics.team_metrics:
            net = (
                f"{tm.net_control_pct * 100:.0f}%"
                if tm.net_control_pct is not None
                else "\u2014"
            )
            pair = (
                f"{tm.avg_pair_distance:.1f}m"
                if tm.avg_pair_distance is not None
                else "\u2014"
            )
            rows += f"""<tr>
<td>{tm.team_id}</td>
<td>{net}</td>
<td>{tm.formation_switches}</td>
<td>{pair}</td>
</tr>"""

        return f"""<table>
<tr><th>Team</th><th>Net Control</th><th>Formation Switches</th><th>Avg Pair Distance</th></tr>
{rows}
</table>"""
