"""
Project: Padex
File Created: 2026-03-08
Author: Xingnan Zhu
File Name: train_event_detector.py
Description:
    Train the MLP event detector (bounce/hit/flying/occluded) from
    weak labels generated by generate_weak_labels.py.

Usage:
    uv run python scripts/train_event_detector.py labels.npz [-o model.pt]

    Supports multiple .npz files for multi-video training:
    uv run python scripts/train_event_detector.py data1.npz data2.npz data3.npz
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("train_event_detector")

LABEL_NAMES = ["flying", "bounce", "hit", "occluded"]


def load_data(paths: list[Path]) -> tuple[np.ndarray, np.ndarray]:
    """Load and concatenate features/labels from multiple .npz files."""
    all_features = []
    all_labels = []
    for p in paths:
        data = np.load(p)
        all_features.append(data["features"])
        all_labels.append(data["labels"])
        logger.info("Loaded %s: %d samples", p.name, len(data["labels"]))
    return np.concatenate(all_features), np.concatenate(all_labels)


def compute_class_weights(labels: np.ndarray, num_classes: int = 4) -> torch.Tensor:
    """Compute inverse-frequency class weights for balanced training."""
    counts = np.bincount(labels, minlength=num_classes).astype(np.float32)
    counts = np.maximum(counts, 1.0)  # avoid division by zero
    weights = 1.0 / counts
    weights /= weights.sum()
    weights *= num_classes  # scale so average weight ≈ 1
    return torch.from_numpy(weights)


def train(
    features: np.ndarray,
    labels: np.ndarray,
    output_path: Path,
    epochs: int = 100,
    batch_size: int = 256,
    lr: float = 1e-3,
    val_split: float = 0.15,
) -> None:
    """Train the EventMLP model."""
    from padex.events.bounce import EventMLP

    n = len(features)
    input_dim = features.shape[1]

    # Shuffle and split
    perm = np.random.default_rng(42).permutation(n)
    val_n = int(n * val_split)
    val_idx, train_idx = perm[:val_n], perm[val_n:]

    X_train = torch.from_numpy(features[train_idx])
    y_train = torch.from_numpy(labels[train_idx])
    X_val = torch.from_numpy(features[val_idx])
    y_val = torch.from_numpy(labels[val_idx])

    train_ds = TensorDataset(X_train, y_train)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

    # Class weights
    class_weights = compute_class_weights(labels)
    logger.info("Class weights: %s", {LABEL_NAMES[i]: f"{w:.2f}" for i, w in enumerate(class_weights)})

    # Model
    model = EventMLP(input_dim=input_dim)
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, patience=10, factor=0.5
    )

    best_val_acc = 0.0
    best_state = None

    for epoch in range(1, epochs + 1):
        # Train
        model.train()
        total_loss = 0.0
        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            loss.backward()
            optimizer.step()
            total_loss += loss.item() * len(X_batch)

        avg_loss = total_loss / len(train_idx)

        # Validate
        model.eval()
        with torch.no_grad():
            val_logits = model(X_val)
            val_preds = val_logits.argmax(dim=1)
            val_acc = float((val_preds == y_val).float().mean())
            val_loss = float(criterion(val_logits, y_val))

        scheduler.step(val_loss)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = model.state_dict().copy()

        if epoch % 10 == 0 or epoch == 1:
            logger.info(
                "Epoch %3d | train_loss=%.4f | val_loss=%.4f | val_acc=%.3f | best=%.3f",
                epoch, avg_loss, val_loss, val_acc, best_val_acc,
            )

    # Save best model
    if best_state is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(best_state, output_path)
        logger.info("Saved best model to %s (val_acc=%.3f)", output_path, best_val_acc)

    # Per-class accuracy on validation set
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        val_preds = model(X_val).argmax(dim=1).numpy()
    y_val_np = y_val.numpy()
    logger.info("--- Per-class validation accuracy ---")
    for cls_id, name in enumerate(LABEL_NAMES):
        mask = y_val_np == cls_id
        if mask.sum() == 0:
            logger.info("  %-10s: no samples", name)
            continue
        acc = float((val_preds[mask] == cls_id).mean())
        logger.info("  %-10s: %.1f%% (%d samples)", name, acc * 100, int(mask.sum()))


def main() -> None:
    # Parse args: one or more .npz files, optional -o output.pt
    args = sys.argv[1:]
    if not args:
        logger.error("Usage: train_event_detector.py <labels.npz> [labels2.npz ...] [-o model.pt]")
        sys.exit(1)

    output_path = Path("output/event_detector.pt")
    npz_paths: list[Path] = []

    i = 0
    while i < len(args):
        if args[i] == "-o" and i + 1 < len(args):
            output_path = Path(args[i + 1])
            i += 2
        else:
            npz_paths.append(Path(args[i]))
            i += 1

    if not npz_paths:
        logger.error("No .npz files provided")
        sys.exit(1)

    features, labels = load_data(npz_paths)
    logger.info("Total samples: %d, feature dim: %d", len(labels), features.shape[1])

    # Distribution
    for cls_id, name in enumerate(LABEL_NAMES):
        count = int((labels == cls_id).sum())
        logger.info("  %-10s: %d (%.1f%%)", name, count, 100.0 * count / len(labels))

    train(features, labels, output_path)


if __name__ == "__main__":
    main()
